const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const Issue = require('../models/Issue.model');
const authenticate = require('../middleware/authenticate');
const authorize = require('../middleware/authorize');

// GET /api/v1/export/issue/:id/pdf — Single issue PDF
router.get('/issue/:id/pdf', authenticate, async (req, res, next) => {
    try {
        const issue = await Issue.findById(req.params.id)
            .populate('reportedBy', 'name');

        if (!issue) return res.status(404).json({ message: 'Issue not found' });

        // Citizens can only export their own issues; admins can export any
        if (req.user.role !== 'admin' && issue.reportedBy._id.toString() !== req.user.id) {
            return res.status(403).json({ message: 'You can only export your own issues' });
        }

        const doc = new PDFDocument({ size: 'A4', margin: 50 });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="issue-${issue._id}.pdf"`);
        doc.pipe(res);

        // Header
        doc.fontSize(22).font('Helvetica-Bold').text('CivicConnect', { align: 'center' });
        doc.fontSize(10).font('Helvetica').fillColor('#666')
            .text('Civic Issue Reporting & Resolution Portal', { align: 'center' });
        doc.moveDown(0.5);
        doc.strokeColor('#1B3FA0').lineWidth(2)
            .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown(1);

        // Issue title
        doc.fontSize(16).font('Helvetica-Bold').fillColor('#1a1a1a')
            .text(issue.title);
        doc.moveDown(0.5);

        // Meta info table
        const meta = [
            ['Issue ID', issue.issueId || issue._id.toString().slice(-8)],
            ['Status', (issue.status || 'submitted').replace('_', ' ').toUpperCase()],
            ['Priority', (issue.priority || 'medium').toUpperCase()],
            ['Category', (issue.category || '').replace('_', ' ').toUpperCase()],
            ['Location', issue.address || 'Not specified'],
            ['Submission Date', new Date(issue.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })],
            ['Reporter', issue.reportedBy?.name ? issue.reportedBy.name.split(' ')[0] : 'Anonymous']
        ];

        doc.fontSize(10).font('Helvetica');
        meta.forEach(([label, value]) => {
            doc.font('Helvetica-Bold').fillColor('#333').text(`${label}: `, { continued: true });
            doc.font('Helvetica').fillColor('#555').text(value);
        });
        doc.moveDown(1);

        // Description
        doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a1a')
            .text('Description');
        doc.moveDown(0.3);
        doc.fontSize(10).font('Helvetica').fillColor('#444')
            .text(issue.description, { align: 'justify' });
        doc.moveDown(1);

        // Photos
        if (issue.photos && issue.photos.length > 0) {
            doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a1a')
                .text('Attached Photos');
            doc.moveDown(0.3);
            issue.photos.forEach((photo, idx) => {
                doc.fontSize(9).font('Helvetica').fillColor('#1B3FA0')
                    .text(`Photo ${idx + 1}: ${photo.url}`, { link: photo.url, underline: true });
            });
            doc.moveDown(1);
        }

        // Admin notes
        if (issue.resolutionNote) {
            doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a1a')
                .text('Admin Notes');
            doc.moveDown(0.3);
            doc.fontSize(10).font('Helvetica').fillColor('#444')
                .text(issue.resolutionNote);
            doc.moveDown(1);
        }

        // Footer
        doc.moveDown(2);
        doc.strokeColor('#ddd').lineWidth(1)
            .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown(0.5);
        doc.fontSize(8).font('Helvetica').fillColor('#999')
            .text(`Generated by CivicConnect | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' });

        doc.end();
    } catch (err) {
        next(err);
    }
});

// GET /api/v1/export/issues/pdf — Batch export (admin only)
router.get('/issues/pdf', authenticate, authorize('admin'), async (req, res, next) => {
    try {
        const { category, status, priority, dateFrom, dateTo } = req.query;

        let query = {};
        if (category) query.category = category;
        if (status) query.status = status;
        if (priority) query.priority = priority;
        if (dateFrom || dateTo) {
            query.createdAt = {};
            if (dateFrom) query.createdAt.$gte = new Date(dateFrom);
            if (dateTo) query.createdAt.$lte = new Date(dateTo);
        }

        const totalCount = await Issue.countDocuments(query);
        const issues = await Issue.find(query)
            .populate('reportedBy', 'name')
            .sort({ createdAt: -1 })
            .limit(100);

        const doc = new PDFDocument({ size: 'A4', margin: 50 });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename="civicconnect-issues-export.pdf"');
        doc.pipe(res);

        // Page 1: Header
        doc.fontSize(22).font('Helvetica-Bold').text('CivicConnect', { align: 'center' });
        doc.fontSize(10).font('Helvetica').fillColor('#666')
            .text('Batch Issues Export Report', { align: 'center' });
        doc.moveDown(0.3);
        doc.fontSize(8).fillColor('#999')
            .text(`Generated: ${new Date().toLocaleDateString()} | Total Matching: ${totalCount}${totalCount > 100 ? ' (showing first 100)' : ''}`, { align: 'center' });
        doc.moveDown(0.5);
        doc.strokeColor('#1B3FA0').lineWidth(2)
            .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown(1);

        // Summary Table Header
        const tableTop = doc.y;
        const colWidths = [55, 130, 75, 60, 65, 60, 55];
        const headers = ['ID', 'Title', 'Category', 'Priority', 'Status', 'Area', 'Date'];
        
        doc.fontSize(8).font('Helvetica-Bold').fillColor('#fff');
        let xPos = 50;
        // Draw header row bg
        doc.rect(50, tableTop - 3, 495, 16).fill('#1B3FA0');
        xPos = 50;
        headers.forEach((header, i) => {
            doc.fillColor('#fff').text(header, xPos + 3, tableTop, { width: colWidths[i] - 6, ellipsis: true });
            xPos += colWidths[i];
        });
        doc.moveDown(0.5);

        // Table rows
        let rowY = tableTop + 18;
        doc.font('Helvetica').fontSize(7).fillColor('#333');

        issues.forEach((issue, idx) => {
            if (rowY > 750) {
                doc.addPage();
                rowY = 50;
            }

            // Alternating row color
            if (idx % 2 === 0) {
                doc.rect(50, rowY - 2, 495, 14).fill('#f8f9fa');
            }

            doc.fillColor('#333');
            xPos = 50;
            const row = [
                issue.issueId || issue._id.toString().slice(-8),
                issue.title,
                (issue.category || '').replace('_', ' '),
                (issue.priority || 'medium'),
                (issue.status || '').replace('_', ' '),
                issue.area || '-',
                new Date(issue.createdAt).toLocaleDateString()
            ];

            row.forEach((cell, i) => {
                doc.text(String(cell), xPos + 3, rowY, { width: colWidths[i] - 6, ellipsis: true });
                xPos += colWidths[i];
            });

            rowY += 14;
        });

        // Detail pages
        issues.forEach((issue, idx) => {
            doc.addPage();

            doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a1a')
                .text(`${issue.issueId || issue._id.toString().slice(-8)} - ${issue.title}`);
            doc.moveDown(0.5);

            doc.fontSize(9).font('Helvetica').fillColor('#555');
            doc.font('Helvetica-Bold').text('Category: ', { continued: true });
            doc.font('Helvetica').text((issue.category || '').replace('_', ' '));
            doc.font('Helvetica-Bold').text('Priority: ', { continued: true });
            doc.font('Helvetica').text(issue.priority || 'medium');
            doc.font('Helvetica-Bold').text('Status: ', { continued: true });
            doc.font('Helvetica').text((issue.status || '').replace('_', ' '));
            doc.font('Helvetica-Bold').text('Location: ', { continued: true });
            doc.font('Helvetica').text(issue.address || 'Not specified');
            doc.moveDown(0.5);

            doc.fontSize(10).font('Helvetica-Bold').fillColor('#1a1a1a').text('Description');
            doc.moveDown(0.3);
            const desc = issue.description || '';
            doc.fontSize(9).font('Helvetica').fillColor('#444')
                .text(desc.length > 500 ? desc.substring(0, 500) + '...' : desc, { align: 'justify' });

            if (issue.resolutionNote) {
                doc.moveDown(0.5);
                doc.fontSize(10).font('Helvetica-Bold').fillColor('#1a1a1a').text('Admin Notes');
                doc.moveDown(0.2);
                doc.fontSize(9).font('Helvetica').fillColor('#444').text(issue.resolutionNote);
            }

            // Footer on each detail page
            doc.fontSize(7).fillColor('#ccc')
                .text(`Page ${idx + 2}`, 50, 780, { align: 'center' });
        });

        doc.end();
    } catch (err) {
        next(err);
    }
});

module.exports = router;
